In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
from sklearn import metrics

In [21]:
df = pd.read_csv(r"C:\Users\jason\Documents\Jerry\Studies\Jerry DSc\archive (3)\HepatitisCdata.csv",index_col=0)

In [22]:
df.head()

Category  Age Sex   ALB   ALP   ALT   AST   BIL    CHE  CHOL   CREA  \
1  0=Blood Donor   32   m  38.5  52.5   7.7  22.1   7.5   6.93  3.23  106.0   
2  0=Blood Donor   32   m  38.5  70.3  18.0  24.7   3.9  11.17  4.80   74.0   
3  0=Blood Donor   32   m  46.9  74.7  36.2  52.6   6.1   8.84  5.20   86.0   
4  0=Blood Donor   32   m  43.2  52.0  30.6  22.6  18.9   7.33  4.74   80.0   
5  0=Blood Donor   32   m  39.2  74.1  32.6  24.8   9.6   9.15  4.32   76.0   

    GGT  PROT  
1  12.1  69.0  
2  15.6  76.5  
3  33.2  79.3  
4  33.8  75.7  
5  29.9  68.7

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 622 entries, 1 to 622
Data columns (total 13 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Category  615 non-null    object 
 1   Age       622 non-null    int64  
 2   Sex       622 non-null    object 
 3   ALB       621 non-null    float64
 4   ALP       602 non-null    float64
 5   ALT       621 non-null    float64
 6   AST       622 non-null    float64
 7   BIL       622 non-null    float64
 8   CHE       622 non-null    float64
 9   CHOL      612 non-null    float64
 10  CREA      622 non-null    float64
 11  GGT       622 non-null    float64
 12  PROT      621 non-null    float64
dtypes: float64(10), int64(1), object(2)
memory usage: 68.0+ KB


In [24]:
df = df.dropna()
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 589 entries, 1 to 613
Data columns (total 13 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Category  589 non-null    object 
 1   Age       589 non-null    int64  
 2   Sex       589 non-null    object 
 3   ALB       589 non-null    float64
 4   ALP       589 non-null    float64
 5   ALT       589 non-null    float64
 6   AST       589 non-null    float64
 7   BIL       589 non-null    float64
 8   CHE       589 non-null    float64
 9   CHOL      589 non-null    float64
 10  CREA      589 non-null    float64
 11  GGT       589 non-null    float64
 12  PROT      589 non-null    float64
dtypes: float64(10), int64(1), object(2)
memory usage: 64.4+ KB


In [25]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Sex']= le.fit_transform(df['Sex'])
df['Category']=le.fit_transform(df['Category'])
df.head()

Category  Age  Sex   ALB   ALP   ALT   AST   BIL    CHE  CHOL   CREA   GGT  \
1         0   32    1  38.5  52.5   7.7  22.1   7.5   6.93  3.23  106.0  12.1   
2         0   32    1  38.5  70.3  18.0  24.7   3.9  11.17  4.80   74.0  15.6   
3         0   32    1  46.9  74.7  36.2  52.6   6.1   8.84  5.20   86.0  33.2   
4         0   32    1  43.2  52.0  30.6  22.6  18.9   7.33  4.74   80.0  33.8   
5         0   32    1  39.2  74.1  32.6  24.8   9.6   9.15  4.32   76.0  29.9   

   PROT  
1  69.0  
2  76.5  
3  79.3  
4  75.7  
5  68.7

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 589 entries, 1 to 613
Data columns (total 13 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Category  589 non-null    int32  
 1   Age       589 non-null    int64  
 2   Sex       589 non-null    int32  
 3   ALB       589 non-null    float64
 4   ALP       589 non-null    float64
 5   ALT       589 non-null    float64
 6   AST       589 non-null    float64
 7   BIL       589 non-null    float64
 8   CHE       589 non-null    float64
 9   CHOL      589 non-null    float64
 10  CREA      589 non-null    float64
 11  GGT       589 non-null    float64
 12  PROT      589 non-null    float64
dtypes: float64(10), int32(2), int64(1)
memory usage: 59.8 KB


In [27]:
df.describe()

Category         Age         Sex         ALB         ALP         ALT  \
count  589.000000  589.000000  589.000000  589.000000  589.000000  589.000000   
mean     0.303905   47.417657    0.616299   41.624278   68.123090   26.575382   
std      0.944552    9.931334    0.486700    5.761794   25.921072   20.863120   
min      0.000000   23.000000    0.000000   14.900000   11.300000    0.900000   
25%      0.000000   39.000000    0.000000   38.800000   52.500000   16.400000   
50%      0.000000   47.000000    1.000000   41.900000   66.200000   22.700000   
75%      0.000000   54.000000    1.000000   45.100000   79.900000   31.900000   
max      4.000000   77.000000    1.000000   82.200000  416.600000  325.300000   

              AST         BIL         CHE        CHOL         CREA  \
count  589.000000  589.000000  589.000000  589.000000   589.000000   
mean    33.772835   11.018166    8.203633    5.391341    81.669100   
std     32.866871   17.406572    2.191073    1.128954    50.696991   
min     10.600000    0.800000    1.420000    1.430000     8.000000   
25%     21.500000    5.200000    6.930000    4.620000    68.000000   
50%     25.700000    7.100000    8.260000    5.310000    77.000000   
75%     31.700000   11.000000    9.570000    6.080000    89.000000   
max    324.000000  209.000000   16.410000    9.670000  1079.100000   

              GGT        PROT  
count  589.000000  589.000000  
mean    38.198472   71.890153  
std     54.302407    5.348883  
min      4.500000   44.800000  
25%     15.600000   69.300000  
50%     22.800000   72.100000  
75%     37.600000   75.200000  
max    650.900000   86.500000

In [28]:
df.corr()

Category       Age       Sex       ALB       ALP       ALT  \
Category  1.000000  0.098125  0.058016 -0.287476  0.036451 -0.150302   
Age       0.098125  1.000000 -0.014288 -0.191094  0.177720 -0.040576   
Sex       0.058016 -0.014288  1.000000  0.150091 -0.007601  0.177107   
ALB      -0.287476 -0.191094  0.150091  1.000000 -0.146120  0.039497   
ALP       0.036451  0.177720 -0.007601 -0.146120  1.000000  0.221603   
ALT      -0.150302 -0.040576  0.177107  0.039497  0.221603  1.000000   
AST       0.652524  0.072739  0.129883 -0.177609  0.067024  0.198658   
BIL       0.520561  0.039655  0.108063 -0.169597  0.058372 -0.106797   
CHE      -0.339909 -0.075863  0.181649  0.360919  0.029482  0.224344   
CHOL     -0.286499  0.124742 -0.030447  0.210420  0.125900  0.149997   
CREA      0.219027 -0.025142  0.158068  0.001433  0.153909 -0.036106   
GGT       0.458155  0.143379  0.128142 -0.147598  0.461300  0.219707   
PROT     -0.064306 -0.159760  0.043296  0.570726 -0.063085  0.016786   

               AST       BIL       CHE      CHOL      CREA       GGT      PROT  
Category  0.652524  0.520561 -0.339909 -0.286499  0.219027  0.458155 -0.064306  
Age       0.072739  0.039655 -0.075863  0.124742 -0.025142  0.143379 -0.159760  
Sex       0.129883  0.108063  0.181649 -0.030447  0.158068  0.128142  0.043296  
ALB      -0.177609 -0.169597  0.360919  0.210420  0.001433 -0.147598  0.570726  
ALP       0.067024  0.058372  0.029482  0.125900  0.153909  0.461300 -0.063085  
ALT       0.198658 -0.106797  0.224344  0.149997 -0.036106  0.219707  0.016786  
AST       1.000000  0.309580 -0.197270 -0.201213 -0.017948  0.477774  0.017404  
BIL       0.309580  1.000000 -0.320713 -0.181570  0.019910  0.210567 -0.052575  
CHE      -0.197270 -0.320713  1.000000  0.428018 -0.012120 -0.095716  0.306288  
CHOL     -0.201213 -0.181570  0.428018  1.000000 -0.051464  0.008823  0.245050  
CREA     -0.017948  0.019910 -0.012120 -0.051464  1.000000  0.125353 -0.030111  
GGT       0.477774  0.210567 -0.095716  0.008823  0.125353  1.000000 -0.037127  
PROT      0.017404 -0.052575  0.306288  0.245050 -0.030111 -0.037127  1.000000

In [29]:
y=df['Category']
y

1      0
2      0
3      0
4      0
5      0
      ..
609    4
610    4
611    4
612    4
613    4
Name: Category, Length: 589, dtype: int32

In [30]:
x=df.drop('Category', axis=1)
x

Age  Sex   ALB    ALP   ALT    AST   BIL    CHE  CHOL   CREA    GGT  PROT
1     32    1  38.5   52.5   7.7   22.1   7.5   6.93  3.23  106.0   12.1  69.0
2     32    1  38.5   70.3  18.0   24.7   3.9  11.17  4.80   74.0   15.6  76.5
3     32    1  46.9   74.7  36.2   52.6   6.1   8.84  5.20   86.0   33.2  79.3
4     32    1  43.2   52.0  30.6   22.6  18.9   7.33  4.74   80.0   33.8  75.7
5     32    1  39.2   74.1  32.6   24.8   9.6   9.15  4.32   76.0   29.9  68.7
..   ...  ...   ...    ...   ...    ...   ...    ...   ...    ...    ...   ...
609   58    0  34.0   46.4  15.0  150.0   8.0   6.26  3.98   56.0   49.7  80.6
610   59    0  39.0   51.3  19.6  285.8  40.0   5.77  4.51  136.1  101.1  70.5
611   62    0  32.0  416.6   5.9  110.3  50.0   5.57  6.30   55.7  650.9  68.5
612   64    0  24.0  102.8   2.9   44.4  20.0   1.54  3.02   63.0   35.9  71.3
613   64    0  29.0   87.3   3.5   99.0  48.0   1.66  3.63   66.7   64.2  82.0

[589 rows x 12 columns]

In [31]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y)

In [32]:
from sklearn.linear_model import LogisticRegression
clr = LogisticRegression()
clr.fit(x_train, y_train)
y_pred = clr.predict(x_test)
y_pred

C:\Users\jason\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 1, 0, 2, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0,
       2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0])

In [33]:
print(confusion_matrix(y_test, y_pred))
accuracy = metrics.accuracy_score(y_test, y_pred)
print(accuracy)
print(metrics.classification_report(y_test, y_pred))

[[137   0   0   0   0]
 [  1   1   0   0   0]
 [  0   0   2   0   0]
 [  0   0   1   1   0]
 [  0   1   0   1   3]]
0.972972972972973
              precision    recall  f1-score   support

           0       0.99      1.00      1.00       137
           1       0.50      0.50      0.50         2
           2       0.67      1.00      0.80         2
           3       0.50      0.50      0.50         2
           4       1.00      0.60      0.75         5

    accuracy                           0.97       148
   macro avg       0.73      0.72      0.71       148
weighted avg       0.98      0.97      0.97       148



In [ ]:
#model.predict() work in progress

In [34]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(x_train, y_train)
y_pred2 = classifier.predict(x_test)
y_pred2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0,
       2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0])

In [35]:
print(confusion_matrix(y_test, y_pred2))
accuracy = metrics.accuracy_score(y_test, y_pred2)
print(accuracy)
print(metrics.classification_report(y_test, y_pred2))

[[137   0   0   0   0]
 [  2   0   0   0   0]
 [  1   0   1   0   0]
 [  0   0   2   0   0]
 [  1   0   1   0   3]]
0.9527027027027027
              precision    recall  f1-score   support

           0       0.97      1.00      0.99       137
           1       0.00      0.00      0.00         2
           2       0.25      0.50      0.33         2
           3       0.00      0.00      0.00         2
           4       1.00      0.60      0.75         5

    accuracy                           0.95       148
   macro avg       0.44      0.42      0.41       148
weighted avg       0.94      0.95      0.94       148



C:\Users\jason\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\jason\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\jason\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [36]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier()
dtc.fit(x_train, y_train)
y_pred3 = dtc.predict(x_test)
y_pred3

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       4, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0])

In [37]:
print(confusion_matrix(y_test, y_pred3))
accuracy = metrics.accuracy_score(y_test, y_pred3)
print(accuracy)
print(metrics.classification_report(y_test, y_pred3))

[[136   0   0   0   1]
 [  0   1   1   0   0]
 [  2   0   0   0   0]
 [  1   0   1   0   0]
 [  1   0   1   0   3]]
0.9459459459459459
              precision    recall  f1-score   support

           0       0.97      0.99      0.98       137
           1       1.00      0.50      0.67         2
           2       0.00      0.00      0.00         2
           3       0.00      0.00      0.00         2
           4       0.75      0.60      0.67         5

    accuracy                           0.95       148
   macro avg       0.54      0.42      0.46       148
weighted avg       0.94      0.95      0.94       148



C:\Users\jason\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\jason\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\jason\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [38]:
from sklearn.ensemble import RandomForestClassifier
classifier_rf = RandomForestClassifier(random_state=42, n_jobs=-1, n_estimators=100)
classifier_rf.fit(x_train, y_train)
y_pred4 = classifier_rf.predict(x_test)
y_pred4

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0,
       2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0])

In [39]:
print(confusion_matrix(y_test, y_pred4))
accuracy = metrics.accuracy_score(y_test, y_pred4)
print(accuracy)
print(metrics.classification_report(y_test, y_pred4))

[[136   1   0   0   0]
 [  1   1   0   0   0]
 [  0   0   2   0   0]
 [  0   0   2   0   0]
 [  0   0   0   0   5]]
0.972972972972973
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       137
           1       0.50      0.50      0.50         2
           2       0.50      1.00      0.67         2
           3       0.00      0.00      0.00         2
           4       1.00      1.00      1.00         5

    accuracy                           0.97       148
   macro avg       0.60      0.70      0.63       148
weighted avg       0.97      0.97      0.97       148



C:\Users\jason\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\jason\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\jason\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [40]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
y_pred5 = gnb.fit(x_train, y_train).predict(x_test)
y_pred5

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 1, 0, 2, 0, 0, 0, 0, 0, 0, 0,
       0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 4, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0])

In [41]:
print(confusion_matrix(y_test, y_pred5))
accuracy = metrics.accuracy_score(y_test, y_pred5)
print(accuracy)
print(metrics.classification_report(y_test, y_pred5))

[[133   1   3   0   0]
 [  0   2   0   0   0]
 [  2   0   0   0   0]
 [  0   0   2   0   0]
 [  0   0   0   0   5]]
0.9459459459459459
              precision    recall  f1-score   support

           0       0.99      0.97      0.98       137
           1       0.67      1.00      0.80         2
           2       0.00      0.00      0.00         2
           3       0.00      0.00      0.00         2
           4       1.00      1.00      1.00         5

    accuracy                           0.95       148
   macro avg       0.53      0.59      0.56       148
weighted avg       0.95      0.95      0.95       148



C:\Users\jason\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\jason\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\jason\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [42]:
from sklearn.naive_bayes import MultinomialNB
mnb = MultinomialNB()
y_pred6 = mnb.fit(x_train, y_train).predict(x_test)
y_pred6

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0,
       3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 2, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0])

In [43]:
print(confusion_matrix(y_test, y_pred6))
accuracy = metrics.accuracy_score(y_test, y_pred6)
print(accuracy)
print(metrics.classification_report(y_test, y_pred6))

[[134   1   1   1   0]
 [  1   1   0   0   0]
 [  0   0   0   2   0]
 [  0   0   2   0   0]
 [  2   1   0   0   2]]
0.9256756756756757
              precision    recall  f1-score   support

           0       0.98      0.98      0.98       137
           1       0.33      0.50      0.40         2
           2       0.00      0.00      0.00         2
           3       0.00      0.00      0.00         2
           4       1.00      0.40      0.57         5

    accuracy                           0.93       148
   macro avg       0.46      0.38      0.39       148
weighted avg       0.94      0.93      0.93       148

